version: '3'

services:
  db:
    image: postgres:18
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: aded
      POSTGRES_PASSWORD: aded
      POSTGRES_USER: aded
    ports:
      - "50432:5432"
volumes:
  pgdata: