CREATE TABLE character
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name              VARCHAR(255) NOT NULL ,
    hp                INTEGER NOT NULL,
    strength          INTEGER NOT NULL,
    defense           INTEGER NOT NULL,
    agility           INTEGER NOT NULL,
    quantity_of_dice  INTEGER NOT NULL,
    faces_of_the_dice INTEGER NOT NULL,
    type              VARCHAR(255) NOT NULL,
    CONSTRAINT pk_character PRIMARY KEY (id)
);