CREATE SEQUENCE IF NOT EXISTS character_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE character
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name              VARCHAR(255),
    hp                INTEGER,
    strength          INTEGER,
    defense           INTEGER,
    agility           INTEGER,
    quantity_of_dice  INTEGER,
    faces_of_the_dice INTEGER,
    type              VARCHAR(255),
    CONSTRAINT pk_character PRIMARY KEY (id)
);