CREATE TABLE history
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    game_id            BIGINT,
    start_character_id BIGINT,
    CONSTRAINT pk_history PRIMARY KEY (id)
);

CREATE TABLE history_turn
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    history_id             BIGINT,
    attacking_character_id BIGINT,
    defender_character_id  BIGINT,
    attack                 INTEGER,
    defense                INTEGER,
    damage                 INTEGER,
    CONSTRAINT pk_historyturn PRIMARY KEY (id)
);

ALTER TABLE history_turn
    ADD CONSTRAINT FK_HISTORYTURN_ON_ATTACKINGCHARACTER FOREIGN KEY (attacking_character_id) REFERENCES character (id);

ALTER TABLE history_turn
    ADD CONSTRAINT FK_HISTORYTURN_ON_DEFENDERCHARACTER FOREIGN KEY (defender_character_id) REFERENCES character (id);

ALTER TABLE history_turn
    ADD CONSTRAINT FK_HISTORYTURN_ON_HISTORY FOREIGN KEY (history_id) REFERENCES history (id);

ALTER TABLE history
    ADD CONSTRAINT FK_HISTORY_ON_GAME FOREIGN KEY (game_id) REFERENCES game (id);

ALTER TABLE history
    ADD CONSTRAINT FK_HISTORY_ON_STARTCHARACTER FOREIGN KEY (start_character_id) REFERENCES character (id);